// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    AddTodo: typeof import('./src/components/Todo/AddTodo.vue')['default']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ARangePicker: typeof import('ant-design-vue/es')['RangePicker']
    ATimePicker: typeof import('ant-design-vue/es')['TimePicker']
    Background: typeof import('./src/components/Background/index.vue')['default']
    Center: typeof import('./src/components/Center/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Todo: typeof import('./src/components/Todo/index.vue')['default']
  }
}
